[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
    elseif executable('gmake')
    let cmd = 'gmake'
    else
    let cmd = 'make'
    endif
    let g:dein#plugin.build = cmd
'''

[[plugins]]
repo = 'Shougo/unite-outline.git'

[[plugins]]
repo = 'Shougo/unite.vim.git'

[[plugins]]
repo = 'Shougo/neocomplete.git'

[[plugins]]
repo = 'Shougo/neobundle.vim.git'

[[plugins]]
repo = 'Shougo/neosnippet.git'

[[plugins]]
repo = 'Shougo/neosnippet-snippets.git'

[[plugins]]
repo = 'thinca/vim-quickrun.git'

[[plugins]]
repo = 'vim-scripts/svndiff.vim.git'

[[plugins]]
repo = 'tpope/vim-surround.git'

[[plugins]]
repo = 'bling/vim-airline.git'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides.git'

[[plugins]]
repo = 'vim-scripts/wombat256.vim.git'

[[plugins]]
repo = '5t111111/alt-gtags.vim'

[[plugins]]
repo = 'Shougo/tabpagebuffer.vim.git'

[[plugins]]
repo = 'tpope/vim-fugitive.git'

[[plugins]]
repo = 'osyo-manga/shabadou.vim.git'

[[plugins]]
repo = 'osyo-manga/vim-watchdogs.git'

[[plugins]]
repo = 'dannyob/quickfixstatus.git'

[[plugins]]
repo = 'KazuakiM/vim-qfstatusline.git'

[[plugins]]
repo = 'tomtom/quickfixsigns_vim'

[[plugins]]
repo = 'itchyny/lightline.vim.git'

[[plugins]]
repo = 'jceb/vim-hier.git'
